### ISSUE TITLE
Entity name 

### ISSUE THREAD

**Issue by wiim23** [j-guyon/CommandSchedulerBundle#124]
Hi, 
It's not a bug but is it possible to rename the entity scheduler-command ? 
Thanks by advance,

**Comment by z31fbras** [comment]
@wiim23 Why would you want to do that?

By the way, maybe you could use import aliasing.
This is something like this:
```php
use JMose\CommandSchedulerBundle\Entity\ScheduledCommand as scheduled_command;
```

**Comment by wiim23** [comment]
In fact, i want to custom the name of the table "scheduled_command" (homogenization with our database schema)

**Comment by z31fbras** [comment]
@wiim23 I think you can do it.
I've never done it though.

Have a look at this link:
[https://symfony.com/doc/current/bundles/override.html#entities-entity-mapping](url)

I think that the file to override should be this one:
[https://github.com/j-guyon/CommandSchedulerBundle/blob/master/Resources/config/doctrine/ScheduledCommand.orm.yml](url)

**Comment by z31fbras** [comment]
@wiim23 You can specify the table name as in this example provided by Doctrine docs:
[https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/yaml-mapping.html#example](url)

**Comment by wiim23** [comment]
thanks for links
i will watch them
