### ISSUE TITLE
Add option to include command namespaces, rather than exclude

### ISSUE THREAD

**Issue by diimpp** [j-guyon/CommandSchedulerBundle#13]
It would useful to include only needed namespaces, rather then keep list of unneeded.

**Comment by Wirone** [comment]
I agree, it would be helpful (in my case I had to exclude almost all namespaces, because I wanted to include only 2).

**Comment by petski** [comment]
Should be fixed with j-guyon/CommandSchedulerBundle#141. Beta version available at https://github.com/petski/CommandSchedulerBundle
