### ISSUE TITLE
cron expression ?

### ISSUE THREAD

**Issue by xorgxx** [j-guyon/CommandSchedulerBundle#130]
Hi can you give same more explanation of how it working [ * * * * * ] ??? i'm complite confus 
for me this 0 0 * ? * * is correspond to "Every hour";  0 0 */8 ? * * | Every eight hours ....

thank

**Comment by llaville** [comment]
If you want to learn more about cron description, please visit site https://crontab.guru/
There are very good (and predefined) examples : https://crontab.guru/examples.html
Hope it will help you.
