### ISSUE TITLE
Update packagist version upon release

### ISSUE THREAD

**Issue by petski** [j-guyon/CommandSchedulerBundle#143]
Idea is to trigger an event towards packagist.org that will trigger them to scrape your repository again. See https://packagist.org/about#how-to-update-packages for details.

Currently packagist.org thinks your latest version is 2.0.2, whereas 2.1.0 was released 15 hours ago. (You can call me impatient now :))

**Comment by j-guyon** [comment]
Done ! The webhook was obsolete indeed 👍
