### ISSUE TITLE
compatibility with doctrine 2

### ISSUE THREAD

**Issue by PhilETaylor** [j-guyon/CommandSchedulerBundle#144]
Please can you consider changing your composer.json to allow 2.0.0-BETA1 of https://github.com/doctrine/DoctrineBundle/releases/tag/2.0.0-Beta1 ??

Yours is the ONLY library in my whole project that moans and doesnt let me bump the version for testing :) :)

**Comment by jeckel** [comment]
Doctrine Bundle 2.0.0 is no more in Beta

**Comment by jeckel** [comment]
There is already on open PR #147
