### ISSUE TITLE
Doctrine 2.7 YamlDriver Depreciation

### ISSUE THREAD

**Issue by fyrye** [j-guyon/CommandSchedulerBundle#149]
The Doctrine ORM mapping YamlDriver is depreciated as of 2.7 and will be removed in 3.0, in favor of using the XMLDriver or AnnotationDriver. [[sic]](https://github.com/doctrine/orm/blob/2.7/UPGRADE.md#deprecated-yaml-mapping-drivers)

**Expected:** 
XML configuration of the ScheduledCommand Entity mapping.

**Comment by drawgas** [comment]
Fix provided. @j-guyon informed. Let's hope this, as well as the composer update to allow recent versions will be merged
