### ISSUE TITLE
Upgrade to support symfony 5.0?

### ISSUE THREAD

**Issue by maikelreyes** [j-guyon/CommandSchedulerBundle#155]
Is scheduled? any date?

**Comment by NicoHaase** [comment]
I support your question, but why not check which steps are needed and provide a PR to this repository? That could be faster than waiting for someone else doing it ;)

**Comment by NicoHaase** [comment]
It looks like this is already started in https://github.com/j-guyon/CommandSchedulerBundle/pull/146

**Comment by alex8444** [comment]
can't make it work on Symfony 5 `    - jmose/command-scheduler-bundle v2.2.0 requires symfony/console ^3.4|^4.0 -> no matching package found.
`

**Comment by Voltisky** [comment]
Same issue here

**Comment by j-guyon** [comment]
Finally merged Symfony 5 support on v3.0.1, sorry for the delay 😅
